detection:
    spam_threshold: 4
    weights:
        subject_keywords: 3
        body_keywords: 2
        caps_ratio: 1.5
        exclamation_ratio: 1
        url_density: 2.5
        html_ratio: 1
        suspicious_headers: 2
        attachment_risk: 1.5
        domain_reputation: 3
        encoding_issues: 1
        from_to_mismatch: 2
        subject_length: 0.5
        frequency_penalty: 2
        word_frequency: 2
        header_validation: 2.5
    keywords:
        high_risk:
            - free money
            - get rich
            - make money fast
            - guaranteed income
            - no risk
            - act now
            - limited time
            - urgent
            - congratulations
            - you have won
            - lottery
            - inheritance
            - nigerian prince
            - viagra
            - cialis
            - pharmacy
            - prescription
        medium_risk:
            - click here
            - visit our website
            - special offer
            - discount
            - save money
            - credit
            - loan
            - mortgage
            - insurance
            - weight loss
            - diet
            - lose weight
            - earn extra
        low_risk:
            - free
            - offer
            - deal
            - sale
            - promotion
            - bonus
            - gift
            - prize
            - winner
            - selected
            - opportunity
    features:
        keyword_detection: true
        header_analysis: true
        attachment_scan: true
        domain_check: true
        frequency_tracking: true
        learning_mode: false
lists:
    whitelist_emails: []
    blacklist_emails: []
    whitelist_domains: []
    blacklist_domains: []
    trusted_domains:
        - gmail.com
        - yahoo.com
        - outlook.com
        - hotmail.com
        - apple.com
        - microsoft.com
        - google.com
        - amazon.com
performance:
    max_concurrent_emails: 10
    timeout_ms: 5000
    cache_size: 1000
    batch_size: 100
logging:
    level: info
    file: ""
    format: text
    max_size_mb: 10
    max_backups: 3
learning:
    enabled: false
    backend: redis
    file:
        model_path: zpam-model.json
        min_word_length: 3
        max_word_length: 20
        case_sensitive: false
        spam_threshold: 0.7
        min_word_count: 2
        smoothing_factor: 1
        use_subject_words: true
        use_body_words: true
        use_header_words: false
        max_vocabulary_size: 10000
    redis:
        redis_url: redis://localhost:6379
        key_prefix: 'zpam:'
        database_num: 0
        osb_window_size: 5
        min_token_length: 3
        max_token_length: 32
        max_tokens: 1000
        min_learns: 200
        max_learns: 5000
        spam_threshold: 0.95
        per_user_stats: true
        default_user: global
        token_ttl: 720h
        cleanup_interval: 6h
        local_cache: true
        cache_ttl: 5m
        batch_size: 100
    auto_train: false
headers:
    enable_spf: true
    enable_dkim: true
    enable_dmarc: true
    dns_timeout_ms: 5000
    max_hop_count: 15
    suspicious_server_score: 75
    auth_weight: 2
    suspicious_weight: 2.5
    spf_fail_penalty: 0.9
    dkim_missing_penalty: 1
    dmarc_missing_penalty: 1.5
    cache_size: 1000
    cache_ttl_min: 60
milter:
    enabled: true
    network: tcp
    address: 127.0.0.1:7357
    read_timeout_ms: 10000
    write_timeout_ms: 10000
    skip_connect: false
    skip_helo: false
    skip_mail: false
    skip_rcpt: false
    skip_headers: false
    skip_body: false
    skip_eoh: false
    skip_data: false
    can_add_headers: true
    can_change_headers: true
    can_add_recipients: true
    can_remove_recipients: false
    can_change_body: true
    can_quarantine: false
    can_change_from: true
    max_concurrent_connections: 10
    graceful_shutdown_timeout_ms: 10000
    reject_threshold: 5
    quarantine_threshold: 4
    reject_message: ""
    quarantine_message: ""
    add_spam_headers: true
    spam_header_prefix: X-ZPAM-
plugins:
    enabled: false
    timeout_ms: 5000
    max_concurrent: 3
    score_method: weighted
    spamassassin:
        enabled: false
        weight: 2
        priority: 1
        timeout_ms: 5000
        settings:
            executable: spamc
            host: localhost
            max_size: 10485760
            port: 783
    rspamd:
        enabled: false
        weight: 2
        priority: 2
        timeout_ms: 3000
        settings:
            password: ""
            url: http://localhost:11334
    custom_rules:
        enabled: false
        weight: 1.5
        priority: 3
        timeout_ms: 1000
        settings:
            rules: []
    virustotal:
        enabled: false
        weight: 3
        priority: 4
        timeout_ms: 10000
        settings:
            api_key: ""
            timeout: 10000
    machine_learning:
        enabled: false
        weight: 2.5
        priority: 5
        timeout_ms: 5000
        settings:
            model_path: ""
            threshold: 0.7
