detection:
    spam_threshold: 5
    weights:
        subject_keywords: 1.5
        body_keywords: 1.2
        caps_ratio: 1.2
        exclamation_ratio: 0.8
        url_density: 0.8
        html_ratio: 0.3
        suspicious_headers: 0.5
        attachment_risk: 0.5
        domain_reputation: 0.1
        encoding_issues: 1
        from_to_mismatch: 2
        subject_length: 0.5
        frequency_penalty: 0.5
        word_frequency: 0.5
        header_validation: 0.1
    keywords:
        high_risk:
            - free money
            - get rich quick
            - make money fast
            - guaranteed income
            - no risk
            - act now
            - limited time
            - urgent
            - congratulations
            - you have won
            - lottery
            - inheritance
            - nigerian prince
            - viagra
            - cialis
            - pharmacy
            - prescription
        medium_risk:
            - click here
            - visit our website
            - special offer
            - discount
            - save money
            - credit
            - loan
            - mortgage
            - insurance
            - weight loss
            - diet
            - lose weight
            - earn extra
        low_risk:
            - free
            - offer
            - deal
            - sale
            - promotion
            - bonus
            - gift
            - prize
            - winner
            - selected
            - opportunity
    features:
        keyword_detection: true
        header_analysis: true
        attachment_scan: true
        domain_check: true
        frequency_tracking: true
        learning_mode: false
lists:
    whitelist_emails: []
    blacklist_emails: []
    whitelist_domains: []
    blacklist_domains: []
    trusted_domains:
        - gmail.com
        - yahoo.com
        - outlook.com
        - hotmail.com
        - apple.com
        - microsoft.com
        - google.com
        - amazon.com
performance:
    max_concurrent_emails: 20
    timeout_ms: 500
    cache_size: 5000
    batch_size: 100
logging:
    level: debug
    file: ""
    format: text
    max_size_mb: 10
    max_backups: 3
learning:
    enabled: true
    model_path: zpo-model.json
    min_word_length: 3
    max_word_length: 20
    case_sensitive: false
    spam_threshold: 0.7
    min_word_count: 2
    smoothing_factor: 1
    use_subject_words: true
    use_body_words: true
    use_header_words: false
    max_vocabulary_size: 10000
    auto_train: false
headers:
    enable_spf: true
    enable_dkim: true
    enable_dmarc: true
    dns_timeout_ms: 5000
    max_hop_count: 15
    suspicious_server_score: 75
    auth_weight: 0.2
    suspicious_weight: 0.2
    spf_fail_penalty: 0.9
    dkim_missing_penalty: 1
    dmarc_missing_penalty: 1.5
    cache_size: 1000
    cache_ttl_min: 60
milter:
    enabled: true
    network: tcp
    address: 127.0.0.1:7357
    read_timeout_ms: 10000
    write_timeout_ms: 10000
    skip_connect: false
    skip_helo: true
    skip_mail: false
    skip_rcpt: false
    skip_headers: false
    skip_body: false
    skip_eoh: true
    skip_data: true
    can_add_headers: true
    can_change_headers: true
    can_add_recipients: true
    can_remove_recipients: false
    can_change_body: true
    can_quarantine: false
    can_change_from: true
    max_concurrent_connections: 10
    graceful_shutdown_timeout_ms: 10000
    reject_threshold: 5
    quarantine_threshold: 4
    reject_message: ""
    quarantine_message: ""
    add_spam_headers: true
    spam_header_prefix: X-ZPO-
plugins:
    enabled: true
    timeout_ms: 5000
    max_concurrent: 3
    score_method: weighted
    spamassassin:
        enabled: false
        weight: 2
        priority: 1
        timeout_ms: 5000
        settings:
            executable: spamc
            host: localhost
            max_size: 10485760
            port: 783
    rspamd:
        enabled: false
        weight: 2
        priority: 2
        timeout_ms: 3000
        settings:
            password: ""
            url: http://localhost:11334
    custom_rules:
        enabled: true
        weight: 1.5
        priority: 3
        timeout_ms: 1000
        settings:
            rules_file: custom_rules.yml
    virustotal:
        enabled: false
        weight: 3
        priority: 4
        timeout_ms: 10000
        settings:
            api_key: ""
            timeout: 10000
    machine_learning:
        enabled: true
        weight: 2.5
        priority: 5
        timeout_ms: 5000
        settings:
            type: simple  # Options: simple, tensorflow, pytorch, sklearn, external
            model_path: "models/spam_classifier"
            confidence_threshold: 0.7
            # TensorFlow-specific settings
            serving_url: http://localhost:8501  # TensorFlow Serving URL
            model_name: spam_classifier
            model_version: "1"
            use_python: true  # Use Python script fallback
            python_script: scripts/tf_inference.py
