version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: zpam-test-redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes --maxmemory 512mb --maxmemory-policy allkeys-lru
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - zpam-test

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: zpam-redis-ui
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - zpam-test
    profiles:
      - ui

  # ZPAM test instance 1
  zpam-test-1:
    build:
      context: ..
      dockerfile: docker/Dockerfile.test
    container_name: zpam-test-instance-1
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - REDIS_URL=redis://redis:6379
      - ZPAM_INSTANCE_ID=instance-1
      - ZPAM_CONFIG_PATH=/app/config-redis.yaml
      - ZPAM_LOG_LEVEL=debug
    volumes:
      - test_results:/app/test_results
      - test_logs:/app/logs
    networks:
      - zpam-test
    profiles:
      - test
    command: ["./test_redis_bayes.sh", "unit"]

  # ZPAM test instance 2 (for multi-instance testing)
  zpam-test-2:
    build:
      context: ..
      dockerfile: docker/Dockerfile.test
    container_name: zpam-test-instance-2
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - REDIS_URL=redis://redis:6379
      - ZPAM_INSTANCE_ID=instance-2
      - ZPAM_CONFIG_PATH=/app/config-redis.yaml
      - ZPAM_LOG_LEVEL=debug
    volumes:
      - test_results:/app/test_results
      - test_logs:/app/logs
    networks:
      - zpam-test
    profiles:
      - test
    command: ["./test_redis_bayes.sh", "integration"]

  # Performance testing instance
  zpam-perf-test:
    build:
      context: ..
      dockerfile: docker/Dockerfile.test
    container_name: zpam-perf-test
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - REDIS_URL=redis://redis:6379
      - ZPAM_INSTANCE_ID=perf-test
      - ZPAM_CONFIG_PATH=/app/config-redis.yaml
      - ZPAM_LOG_LEVEL=info
    volumes:
      - test_results:/app/test_results
      - test_logs:/app/logs
    networks:
      - zpam-test
    profiles:
      - perf
    command: ["./test_redis_bayes.sh", "performance"]

volumes:
  redis_data:
    driver: local
  test_results:
    driver: local
  test_logs:
    driver: local

networks:
  zpam-test:
    driver: bridge 