version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: zpam-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - zpam-network

  zpam:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    restart: unless-stopped
    ports:
      - "7357-7360:7357"
    volumes:
      - ../config-redis.yaml:/app/config.yaml:ro
      - ../custom_rules.yml:/app/custom_rules.yml:ro
      - ../../zpam-test-data:/app/test-data:ro
      - ../../zpam-test-data/stress-test:/app/stress-test:ro
      - zpam_data:/app/data
      - zpam_logs:/app/logs
      - zpam_models:/app/models
    environment:
      - ZPAM_CONFIG_PATH=/app/config.yaml
      - ZPAM_LOG_LEVEL=info
      - REDIS_URL=redis://redis:6379
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "timeout", "5s", "/app/zpam", "--help"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - zpam-network

volumes:
  redis_data:
    driver: local
  zpam_data:
    driver: local
  zpam_logs:
    driver: local
  zpam_models:
    driver: local

networks:
  zpam-network:
    driver: bridge 